name: Тестирование и развертывание проекта
on:
    push:
        branches:
            - main

jobs:
    tests:
        runs-on: ubuntu-22.04
        env:
            ALLOWED_HOSTD: ${{ secrets.ALLOWED_HOSTS }}
            SECRET_KEY: ${{ secrets.SECRET_KEY }}
            DEBUG: ${{ secrets.DEBUG }}
            DB_NAME: ${{ secrets.DB_NAME }}
            DB_USER: ${{ secrets.DB_USER }}
            DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
            DB_HOST: ${{ secrets.DB_HOST }}
            DB_PORT: ${{ secrets.DB_PORT }} 
        service:
            postgresql_main:
                image: postgres:12
                env:
                    POSTGRES_DB: ${{ env.DB_NAME }}
                    POSTGRES_USER: ${{ env.DB_USER }}
                    POSTGRES_PASSWORD: ${{ env.DB_PASSWORD }}
                port:
                    - 5432:5432
                options: 
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5 
        steps:
            - uses: actions/checkout@v3
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: 3.10

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: Lint with flake8
              run: flake8 stocks_products/logistic/ --exclude=stocks_products/logistic/migrations/

            - name: Test with pytest
              run: python manage.py test
              env:
                  ALLOWED_HOSTS: ${{ env.ALLOWED_HOSTS }}
                  SECRET_KEY: ${{ env.SECRET_KEY }}
                  DEBUG: ${{ env.DEBUG }}
                  DB_NAME: ${{ env.DB_NAME }}
                  DB_USER: ${{ env.DB_USER }}
                  DB_PASSWORD: ${{ env.DB_PASSWORD }}
                  DB_HOST: ${{ env.DB_HOST }}
                  DB_PORT: ${{ env.DB_PORT }}
                          
